In [ ]:
#printing type and converting all data types into arrays using numpy
import numpy as n
l1=[1,2,3,4,5.6,6]
t1=(1,2,3,4,5,6)
s1={1,2,3,4,5,6}
str1="I love india."
arr=n.array(l1)
arr2=n.array(t1)
arr3=n.array(s1)
arr4=n.array(str1)
print(arr)
print(arr2)
print(arr3)
print(arr4)
print(type(arr))
print(type(arr2))
print(type(arr3))
print(type(arr4))
t=tuple(arr2)
print(t)
print(type(t))
st=str(arr4)
print(st)
print(type(st))
arr.dtype
arr2.dtype
arr3.dtype
arr4.dtype

[1.  2.  3.  4.  5.6 6. ]
[1 2 3 4 5 6]
{1, 2, 3, 4, 5, 6}
I love india.
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(1, 2, 3, 4, 5, 6)
<class 'tuple'>
I love india.
<class 'str'>


dtype('<U13')

In [4]:
#To convert dictionary to array
import numpy as np
dict_1={
    'name':'Ram',
    'age':20
}
arr11=np.array(dict_1)
print(arr11)
arr11.dtype

{'name': 'Ram', 'age': 20}


dtype('O')

In [6]:
#To perform operations on all elements in array
arr=np.array([1,2,3,4,5,6])
print(arr*2) #multiplying with 2
print(arr/3) #dividing with 3

[ 2  4  6  8 10 12]
[0.33333333 0.66666667 1.         1.33333333 1.66666667 2.        ]


In [7]:
#printing all datatype of a list which are converted into arrray by numpy
for i in arr:
  print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [8]:
#Add element at last to an array
arr=np.append(arr,[1.1,1.2,1.3])
print(arr)

[1.  2.  3.  4.  5.  6.  1.1 1.2 1.3]


In [9]:
#Add element at a particular position
arra=np.insert(arr,0,111)
print(arra)

[111.    1.    2.    3.    4.    5.    6.    1.1   1.2   1.3]


In [10]:
#Add element at multiple particular positions
arra=np.insert(arr,[1,3,5,7],[222,333,444,555])
print(arra)

[  1.  222.    2.    3.  333.    4.    5.  444.    6.    1.1 555.    1.2
   1.3]


In [11]:
#To delete a pariticular value
p=np.delete(arra,np.where(arra==3))
print(p)

[  1.  222.    2.  333.    4.    5.  444.    6.    1.1 555.    1.2   1.3]


In [12]:
#To delete a multiple values at multiple indexes
p=np.delete(arra,[1,2,4])
print(p)

[  1.    3.    4.    5.  444.    6.    1.1 555.    1.2   1.3]


In [13]:
#To delete a multiple value
p=np.setdiff1d(arra,[1,4])
print(p)

[  1.1   1.2   1.3   2.    3.    5.    6.  222.  333.  444.  555. ]


In [14]:
#filter values using numpy by book
l=[1,2,3,4,6]
ar=np.array(l)
print(ar<6) #prints true when condition is true else false

[ True  True  True  True False]


In [15]:
#filter values using numpy
print(ar[ar<5]) #To get values

[1 2 3 4]


In [16]:
#To print specific values which satisfies given condition in bool
l=[5,10,15,20,25,30,35,40,45,50,55,60]
a=np.array(l)
print((a>20)&(a<50))

[False False False False  True  True  True  True  True False False False]


In [17]:
#To print specific values which satisfies given condition
l=[5,10,15,20,25,30,35,40,45,50,55,60]
a=np.array(l)
a[(a>20)&(a<50)]

array([25, 30, 35, 40, 45])

In [18]:
#To replace value
a[a==25]=95
print(a)

[ 5 10 15 20 95 30 35 40 45 50 55 60]


In [19]:
#To create arrays of zeroes 1d
print(np.zeros(6))
#To create arrays of zeroes 2d
print(np.zeros([5,5]))

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
#To create arrays of ones 1d
print(np.ones(6))
#To create arrays of ones 2d
print(np.ones([5,5]))

[1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
#To find the datatype using numpy
arr.dtype

dtype('float64')

In [22]:
#To print dtype of a integer array
print(a.dtype)
print(a)

int64
[ 5 10 15 20 95 30 35 40 45 50 55 60]


Type casting of arrays

In [23]:
#To change size of a datatype
a=np.zeros([2,4],dtype='float16')
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float16)

In [24]:
#To convert datatype after array creation
np.int16(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [25]:
#To create array of range 50
n=np.array(range(1,51))
print(n)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [26]:
#To convert 1d to multi-dimensional array
nn=n.reshape(5,10)
print(nn)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [27]:
#To print identity matrix of multi-dimensional array
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
#To perform slicing in multidimensional array
#syntax: array_name[row,start:end]
print(nn[1,2:6])

[13 14 15 16]


In [29]:
#To find mean
# syntax:numpy.mean(array_name)
l=[1,2,3,4,5,6,7]
a=np.array(l)
print(np.mean(a))

4.0


In [35]:
#To find median
# syntax:numpy.median(array_name)
l=[1,2,3,4,5,6,7] #for even no of elements in array
a=np.array(l)
print(np.median(a))
l1=[1,2,3,4,5,6,7,8] #for even no of elements in array
a=np.array(l)
print(np.median(a))

4.0
4.0


In [32]:
#To find sum
#syntax:numpy.sum(array_name)
l=[1,2,3,4,5,6,7]
a=np.array(l)
print(np.sum(a))

28


In [33]:
#To find variance
#syntax:numpy.var(array_name)
l=[1,2,3,4,5,6,7]
a=np.array(l)
print(np.var(a))

4.0


In [34]:
#To find standard deviation
#syntax:numpy.std(array_name)
l=[1,2,3,4,5,6,7]
a=np.array(l)
print(np.std(a))

2.0
